// frontend/src/App.jsx
import React, { useState, useEffect } from "react";
import ImageGallery from "./components/ImageGallery";
import { getImages, uploadImage } from "./api";
import "./App.css";

function App() {
  const [images, setImages] = useState([]);
  const [file, setFile] = useState(null);
  const [title, setTitle] = useState("");
  const [loading, setLoading] = useState(false);

  // Fetch images
  const fetchImages = async () => {
    try {
      const res = await getImages();
      setImages(res.data);
    } catch (err) {
      console.error("Error fetching images:", err);
    }
  };

  useEffect(() => {
    fetchImages();
  }, []);

  const handleFileChange = (e) => setFile(e.target.files[0]);
  const handleTitleChange = (e) => setTitle(e.target.value);

  const handleUpload = async () => {
    if (!file) {
      alert("Please select an image");
      return;
    }

    const formData = new FormData();
    formData.append("image", file);
    formData.append("name", title || file.name);

    setLoading(true);
    try {
      await uploadImage(formData);
      setFile(null);
      setTitle("");
      fetchImages();
    } catch (err) {
      console.error("Upload error:", err);
      alert("Could not upload image");
    }
    setLoading(false);
  };

  const handleDelete = async (id) => {
    try {
      await fetch(`http://localhost:5000/api/images/${id}`, {
        method: "DELETE",
      });
      fetchImages();
    } catch (err) {
      console.error("Delete failed:", err);
      alert("Delete failed");
    }
  };

  return (
    <div style={{ padding: "20px", fontFamily: "Arial, sans-serif" }}>
      <h1>Advanced Image Viewer</h1>

      {/* Upload Section */}
      <div style={{ marginBottom: "20px" }}>
        <input
          type="text"
          placeholder="Image title"
          value={title}
          onChange={handleTitleChange}
          style={{ marginRight: "10px" }}
        />

        <input
          type="file"
          onChange={handleFileChange}
          style={{ marginRight: "10px" }}
        />

        <button onClick={handleUpload} disabled={loading}>
          {loading ? "Uploading..." : "Upload Image"}
        </button>
      </div>

      {/* Image Gallery */}
      <ImageGallery images={images} setImages={setImages} />

<h3>{image.name}</h3>

            <button onClick={() => handleDelete(image._id)}>
              Delete
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<template>
  <div class="min-h-screen bg-gray-100">
    <h1 class="text-4xl font-bold text-blue-700 text-center mt-8">📸 Image Viewer</h1>

    <form @submit.prevent="uploadImage" class="text-center mt-4">
      <input type="file" ref="fileInput" />
      <button type="submit" class="ml-2 px-4 py-2 bg-blue-500 text-white rounded">Upload</button>
    </form>

    <ImageGrid :images="images" @open="openModal" />
    <ImageModal v-if="showModal" :show="showModal" :image="images[currentIndex]" @close="closeModal"/>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import ImageGrid from './components/ImageGrid.vue'
import ImageModal from './components/ImageModal.vue'

const API = import.meta.env.VITE_API_URL

const images = ref([])
const showModal = ref(false)
const currentIndex = ref(0)
const fileInput = ref(null)

async function loadImages() {
  try {
    const res = await fetch(`${API}/images`)
    images.value = await res.json()
  } catch (err) {
    console.error('Error fetching images:', err)
  }
}

async function uploadImage() {
  if (!fileInput.value.files.length) return alert('Choose an image!')

  const formData = new FormData()
  formData.append('image', fileInput.value.files[0])

  try {
    await fetch(`${API}/upload`, { method: 'POST', body: formData })
    fileInput.value.value = ''
    loadImages()
  } catch (err) {
    console.error('Upload failed:', err)
  }
}

function openModal(idx) {
  currentIndex.value = idx
  showModal.value = true
}

function closeModal() {
  showModal.value = false
}

onMounted(() => loadImages())
</script>
